# docker-compose.yml

version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - user_book7-db:/var/lib/postgresql/data

  user_book7:
    build:
      context: ./userbook
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - "5000:5000"

  ui:
    build: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - user_book7

volumes:
  user_book7-db:
